FROM node:16-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV NODE_ENV =production
COPY ["package.json","package-lock.json","./"]
RUN npm install --production 
COPY . . 
EXPOSE 3000
CMD [ "npm","start"] 