//* Authentication
export const REGISTER_API_START = "REGISTER_API_START";
export const REGISTER_API_SUCCESS = "REGISTER_API_SUCCESS";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const LOGIN_API_START = "LOGIN_API_START";
export const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const LOGIN_GOOGLE_START = "LOGIN_GOOGLE_START";
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_FAIL = "LOGIN_GOOGLE_FAIL";

export const LOGOUT_API_START = "LOGOUT_API_START";
export const LOGOUT_API_SUCCESS = "LOGOUT_API_SUCCESS";
export const LOGOUT_API_FAIL = "LOGOUT_API_FAIL";

export const FORGET_PASS_START = "FORGET_PASS_START";
export const FORGET_PASS_SUCCESS = "FORGET_PASS_SUCCESS";
export const FORGET_PASS_FAIL = "FORGET_PASS_FAIL";

export const REFRESH_TOKEN_ADMIN_START = "REFRESH_TOKEN_ADMIN_START";
export const REFRESH_TOKEN_ADMIN_SUCCESS = "REFRESH_TOKEN_ADMIN_SUCCESS";
export const REFRESH_TOKEN_ADMIN_FAIL = "REFRESH_TOKEN_ADMIN_FAIL";

export const GET_PROFILE_START = " GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = " GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = " GET_PROFILE_FAIL";

export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const CLEAR_ERRORS_SUCCESS = "CLEAR_ERRORS_SUCCESS";
