//* Authentication
export const REGISTER_API_START = "REGISTER_API_START";
export const REGISTER_API_SUCCESS = "REGISTER_API_SUCCESS";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const LOGIN_API_START = "LOGIN_API_START";
export const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const LOGIN_GOOGLE_START = "LOGIN_GOOGLE_START";
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_FAIL = "LOGIN_GOOGLE_FAIL";

export const LOGIN_FACEBOOK_START = "LOGIN_FACEBOOK_START";
export const LOGIN_FACEBOOK_SUCCESS = "LOGIN_FACEBOOK_SUCCESS";
export const LOGIN_FACEBOOK_FAIL = "LOGIN_FACEBOOK_FAIL";

export const LOGOUT_API_START = "LOGOUT_API_START";
export const LOGOUT_API_SUCCESS = "LOGOUT_API_SUCCESS";
export const LOGOUT_API_FAIL = "LOGOUT_API_FAIL";

export const FORGET_PASS_START = "FORGET_PASS_START";
export const FORGET_PASS_SUCCESS = "FORGET_PASS_SUCCESS";
export const FORGET_PASS_FAIL = "FORGET_PASS_FAIL";

export const REFRESH_TOKEN_START = "REFRESH_TOKEN_START";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

export const GET_PROFILE_START = " GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = " GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = " GET_PROFILE_FAIL";

export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const NEW_PASSWORD_START = "NEW_PASSWORD_START";
export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS";
export const NEW_PASSWORD_FAIL = "NEW_PASSWORD_FAIL";

export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const GET_ALL_FAVOURITE_START = "GET_ALL_FAVOURITE_START";
export const GET_ALL_FAVOURITE_SUCCESS = "GET_ALL_FAVOURITE_SUCCESS";
export const GET_ALL_FAVOURITE_FAIL = "GET_ALL_FAVOURITE_FAIL";

export const CLEAR_ERRORS_SUCCESS = "CLEAR_ERRORS_SUCCESS";
export const CLEAR_ERRORS_DETAIL_SUCCESS = "CLEAR_ERRORS_DETAIL_SUCCESS";
//* ADMIN
export const REGISTER_ADMIN_API_START = "REGISTER_ADMIN_API_START";
export const REGISTER_ADMIN_API_SUCCESS = "REGISTER_ADMIN_API_SUCCESS";
export const REGISTER_ADMIN_API_FAIL = "REGISTER_ADMIN_API_FAIL";

export const ADMIN_LOGIN_API_START = "ADMIN_LOGIN_API_START";
export const ADMIN_LOGIN_API_SUCCESS = "ADMIN_LOGIN_API_SUCCESS";
export const ADMIN_LOGIN_API_FAIL = "ADMIN_LOGIN_API_FAIL";

export const ADMIN_LOGIN_GOOGLE_START = "ADMIN_LOGIN_GOOGLE_START";
export const ADMIN_LOGIN_GOOGLE_SUCCESS = "ADMIN_LOGIN_GOOGLE_SUCCESS";
export const ADMIN_LOGIN_GOOGLE_FAIL = "ADMIN_LOGIN_GOOGLE_FAIL";

export const ADMIN_LOGOUT_API_START = "ADMIN_LOGOUT_API_START";
export const ADMIN_LOGOUT_API_SUCCESS = "ADMIN_LOGOUT_API_SUCCESS";
export const ADMIN_LOGOUT_API_FAIL = "ADMIN_LOGOUT_API_FAIL";

export const FORGET_ADMIN_START = "FORGET_ADMIN_START";
export const FORGET_ADMIN_SUCCESS = "FORGET_ADMIN_SUCCESS";
export const FORGET_ADMIN_FAIL = "FORGET_ADMIN_FAIL";

export const ADMIN_RESET_PASSWORD_START = "ADMIN_RESET_PASSWORD_START";
export const ADMIN_RESET_PASSWORD_SUCCESS = "RESET_ADMIN_PASSWORD_SUCCESS";
export const ADMIN_RESET_PASSWORD_FAIL = "RESET_ADMIN_PASSWORD_FAIL";

export const ACCEPT_TOKEN_GET_ADMIN_START = "ACCEPT_TOKEN_GET_ADMIN_START";
export const ACCEPT_TOKEN_GET_ADMIN_SUCCESS = "ACCEPT_TOKEN_GET_ADMIN_SUCCESS";
export const ACCEPT_TOKEN_GET_ADMIN_FAIL = "ACCEPT_TOKEN_GET_ADMIN_FAIL";

export const GET_ADMIN_PROFILE_START = " GET_ADMIN_PROFILE_START";
export const GET_ADMIN_PROFILE_SUCCESS = " GET_ADMIN_PROFILE_SUCCESS";
export const GET_ADMIN_PROFILE_FAIL = " GET_ADMIN_PROFILE_FAIL";

export const ADMIN_REFRESH_TOKEN_START = "ADMIN_REFRESH_TOKEN_START";
export const ADMIN_REFRESH_TOKEN_SUCCESS = "ADMIN_REFRESH_TOKEN_SUCCESS";
export const ADMIN_REFRESH_TOKEN_FAIL = "ADMIN_REFRESH_TOKEN_FAIL";

export const CHANGE_ADMIN_PASSWORD_START = "CHANGE_ADMIN_PASSWORD_START";
export const CHANGE_ADMIN_PASSWORD_SUCCESS = "CHANGE_ADMIN_PASSWORD_SUCCESS";
export const CHANGE_ADMIN_PASSWORD_FAIL = "CHANGE_ADMIN_PASSWORD_FAIL";

export const GET_ALL_DIRECTOR_START = "GET_ALL_DIRECTOR_START";
export const GET_ALL_DIRECTOR_SUCCESS = "GET_ALL_DIRECTOR_SUCCESS";
export const GET_ALL_DIRECTOR_FAIL = "GET_ALL_DIRECTOR_FAIL";

export const GET_ALL_USERS_START = "GET_ALL_USERS_START";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
//*Film Admin
export const GET_ALL_CATEGORY_START = "GET_ALL_CATEGORY_START";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAIL = "GET_ALL_CATEGORY_FAIL";

export const GET_ALL_FILM_START = "GET_ALL_FILM_START";
export const GET_ALL_FILM_SUCCESS = "GET_ALL_FILM_SUCCESS";
export const GET_ALL_FILM_FAIL = "GET_ALL_FILM_FAIL";

export const GET_ALL_RATE_START = "GET_ALL_RATE_START";
export const GET_ALL_RATE_SUCCESS = "GET_ALL_RATE_SUCCESS";
export const GET_ALL_RATE_FAIL = "GET_ALL_RATE_FAIL";

export const GET_ALL_SERIESFILM_START = "GET_ALL_SERIESFILM_START";
export const GET_ALL_SERIESFILM_SUCCESS = "GET_ALL_SERIESFILM_SUCCESS";
export const GET_ALL_SERIESFILM_FAIL = "GET_ALL_SERIESFILM_FAIL";

export const FIND_FILM_START = "FIND_FILM_START";
export const FIND_FILM_SUCCESS = "FIND_FILM_SUCCESS";
export const FIND_FILM_FAIL = "FIND_FILM_FAIL";

export const FIND_FILM_CATEGORY_START = "FIND_FILM_CATEGORY_START";
export const FIND_FILM_CATEGORY_SUCCESS = "FIND_FILM_CATEGORY_SUCCESS";
export const FIND_FILM_CATEGORY_FAIL = "FIND_FILM_CATEGORY_FAIL";

//*feedback

export const SEND_FEEDBACK_START = "SEND_FEEDBACK_START";
export const SEND_FEEDBACK_SUCCESS = "SEND_FEEDBACK_SUCCESS";
export const SEND_FEEDBACK_FAIL = "SEND_FEEDBACK_FAIL";
//* get all feedback
export const GET_FEEDBACK_START = "GET_FEEDBACK_START";
export const GET_FEEDBACK_SUCCESS = "GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_FAIL = "GET_FEEDBACK_FAIL";

//* reset comment
export const CLEAR_ERRORS_COMMENT = "CLEAR_ERRORS_COMMENT";

//*GET comment
export const GET_COMMENTS_START = "GET_COMMENTS_START";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

// * ADD comment
export const ADD_COMMENTS_START = "ADD_COMMENTS_START";
export const ADD_COMMENTS_SUCCESS = "ADD_COMMENTS_SUCCESS";
export const ADD_COMMENTS_FAIL = "ADD_COMMENTS_FAIL";

//* UPDATE comment
export const UPDATE_COMMENTS_START = "UPDATE_COMMENTS_START";
export const UPDATE_COMMENTS_SUCCESS = "UPDATE_COMMENTS_SUCCESS";
export const UPDATE_COMMENTS_FAIL = "UPDATE_COMMENTS_FAIL";

//* REMOVE comment
export const REMOVE_COMMENTS_START = "REMOVE_COMMENTS_START";
export const REMOVE_COMMENTS_SUCCESS = "REMOVE_COMMENTS_SUCCESS";
export const REMOVE_COMMENTS_FAIL = "REMOVE_COMMENTS_FAIL";

//* Get all rating 
export const GET_ALL_RATING_START = "GET_ALL_RATING_START";
export const GET_ALL_RATING_SUCCESS = "GET_ALL_RATING_SUCCESS";
export const GET_ALL_RATING_FAIL = "GET_ALL_RATING_FAIL";

//* Add rating
export const ADD_RATING_START = "ADD_RATING_START";
export const ADD_RATING_SUCCESS = "ADD_RATING_SUCCESS";
export const ADD_RATING_FAIL = "ADD_RATING_FAIL";

//* Get favourite film 
export const GET_FAV_START = "GET_FAV_START";
export const GET_FAV_SUCCESS = "GET_FAV_SUCCESS";
export const GET_FAV_FAIL = "GET_FAV_FAIL";

//* Toggle or remove fav
export const TOGGLE_FAV_START = "TOGGLE_FAV_START";
export const TOGGLE_FAV_SUCCESS = "TOGGLE_FAV_SUCCESS";
export const TOGGLE_FAV_FAIL = "TOGGLE_FAV_FAIL";

//*ReplyFeedback
export const REPLY_FEEDBACK_START = "REPLY_FEEDBACK_START";
export const REPLY_FEEDBACK_SUCCESS = "REPLY_FEEDBACK_SUCCESS";
export const REPLY_FEEDBACK_FAIL = "REPLY_FEEDBACK_FAIL";
//* Upload Adult
export const UPLOAD_ADULT_START = "UPLOAD_ADULT_START ";
export const UPLOAD_ADULT_SUCCESS = "UPLOAD_ADULT_SUCCESS";
export const UPLOAD_ADULT_FAIL = "UPLOAD_ADULT_FAIL";
//*Get All Adult
export const GET_ALL_ADULT_START = "GET_ALL_ADULT_START ";
export const GET_ALL_ADULT_SUCCESS = "GET_ALL_ADULT_SUCCESS";
export const GET_ALL_ADULT_FAIL = "GET_ALL_ADULT_FAIL";
//*Get All Kid
export const GET_ALL_KID_START = "GET_ALL_KID_START ";
export const GET_ALL_KID_SUCCESS = "GET_ALL_KID_SUCCESS";
export const GET_ALL_KID_FAIL = "GET_ALL_KID_FAIL";
//*Get login KId
export const LOGIN_KID_START = "LOGIN_KID_START ";
export const LOGIN_KID_SUCCESS = "LOGIN_KID_SUCCESS";
export const LOGIN_KID_FAIL = "LOGIN_KID_FAIL";

// Film Adult
//film adult
export const GET_FILM_CATEGORY_ADULT_START = "GET_FILM_CATEGORY_ADULT_START";
export const GET_FILM_CATEGORY_ADULT_SUCCESS ="GET_FILM_CATEGORY_ADULT_SUCCESS";
export const GET_FILM_CATEGORY_ADULT_FAIL = "GET_FILM_CATEGORY_ADULT_FAIL";

export const GET_FILM_CATEGORY_KID_START = "GET_FILM_CATEGORY_KID_START";
export const GET_FILM_CATEGORY_KID_SUCCESS = "GET_FILM_CATEGORY_KID_SUCCESS";
export const GET_FILM_CATEGORY_KID_FAIL = "GET_FILM_CATEGORY_KID_FAIL";


//Information Director
export const GET_INFORMATION_DIRECTOR_START = "GET_INFORMATION_DIRECTOR_START";
export const GET_INFORMATION_DIRECTOR_SUCCESS = "GET_INFORMATION_DIRECTOR_SUCCESS";
export const GET_INFORMATION_DIRECTOR_FAIL = "GET_INFORMATION_DIRECTOR_FAIL";
//Detail Information Director
export const GET_DETAIL_INFORMATION_DIRECTOR_START = "GET_DETAIL_INFORMATION_DIRECTOR_START";
export const GET_DETAIL_INFORMATION_DIRECTOR_SUCCESS = "GET_DETAIL_INFORMATION_DIRECTOR_SUCCESS";
export const GET_DETAIL_INFORMATION_DIRECTOR_FAIL = "GET_DETAIL_INFORMATION_DIRECTOR_FAIL";