//* Authentication
export const REGISTER_API_START = "REGISTER_API_START";
export const REGISTER_API_SUCCESS = "REGISTER_API_SUCCESS";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const LOGIN_API_START = "LOGIN_API_START";
export const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const LOGIN_GOOGLE_START = "LOGIN_GOOGLE_START";
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
export const LOGIN_GOOGLE_FAIL = "LOGIN_GOOGLE_FAIL";

export const LOGOUT_API_START = "LOGOUT_API_START";
export const LOGOUT_API_SUCCESS = "LOGOUT_API_SUCCESS";
export const LOGOUT_API_FAIL = "LOGOUT_API_FAIL";

export const FORGET_PASS_START = "FORGET_PASS_START";
export const FORGET_PASS_SUCCESS = "FORGET_PASS_SUCCESS";
export const FORGET_PASS_FAIL = "FORGET_PASS_FAIL";

export const REFRESH_TOKEN_START = "REFRESH_TOKEN_START";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

export const GET_PROFILE_START = " GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = " GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = " GET_PROFILE_FAIL";

export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const CLEAR_ERRORS_SUCCESS = "CLEAR_ERRORS_SUCCESS";
//* ADMIN
export const REGISTER_ADMIN_API_START = "REGISTER_ADMIN_API_START";
export const REGISTER_ADMIN_API_SUCCESS = "REGISTER_ADMIN_API_SUCCESS";
export const REGISTER_ADMIN_API_FAIL = "REGISTER_ADMIN_API_FAIL";

export const ADMIN_LOGIN_API_START = "ADMIN_LOGIN_API_START";
export const ADMIN_LOGIN_API_SUCCESS = "ADMIN_LOGIN_API_SUCCESS";
export const ADMIN_LOGIN_API_FAIL = "ADMIN_LOGIN_API_FAIL";

export const ADMIN_LOGIN_GOOGLE_START = "ADMIN_LOGIN_GOOGLE_START";
export const ADMIN_LOGIN_GOOGLE_SUCCESS = "ADMIN_LOGIN_GOOGLE_SUCCESS";
export const ADMIN_LOGIN_GOOGLE_FAIL = "ADMIN_LOGIN_GOOGLE_FAIL";

export const ADMIN_LOGOUT_API_START = "ADMIN_LOGOUT_API_START";
export const ADMIN_LOGOUT_API_SUCCESS = "ADMIN_LOGOUT_API_SUCCESS";
export const ADMIN_LOGOUT_API_FAIL = "ADMIN_LOGOUT_API_FAIL";

export const FORGET_ADMIN_START = "FORGET_ADMIN_START";
export const FORGET_ADMIN_SUCCESS = "FORGET_ADMIN_SUCCESS";
export const FORGET_ADMIN_FAIL = "FORGET_ADMIN_FAIL";

export const ADMIN_RESET_PASSWORD_START = "ADMIN_RESET_PASSWORD_START";
export const ADMIN_RESET_PASSWORD_SUCCESS = "RESET_ADMIN_PASSWORD_SUCCESS";
export const ADMIN_RESET_PASSWORD_FAIL = "RESET_ADMIN_PASSWORD_FAIL";

export const ACCEPT_TOKEN_GET_ADMIN_START = "ACCEPT_TOKEN_GET_ADMIN_START";
export const ACCEPT_TOKEN_GET_ADMIN_SUCCESS = "ACCEPT_TOKEN_GET_ADMIN_SUCCESS";
export const ACCEPT_TOKEN_GET_ADMIN_FAIL = "ACCEPT_TOKEN_GET_ADMIN_FAIL";

export const GET_ADMIN_PROFILE_START = " GET_ADMIN_PROFILE_START";
export const GET_ADMIN_PROFILE_SUCCESS = " GET_ADMIN_PROFILE_SUCCESS";
export const GET_ADMIN_PROFILE_FAIL = " GET_ADMIN_PROFILE_FAIL";

export const ADMIN_REFRESH_TOKEN_START = "ADMIN_REFRESH_TOKEN_START";
export const ADMIN_REFRESH_TOKEN_SUCCESS = "ADMIN_REFRESH_TOKEN_SUCCESS";
export const ADMIN_REFRESH_TOKEN_FAIL = "ADMIN_REFRESH_TOKEN_FAIL";

export const CHANGE_ADMIN_PASSWORD_START = "CHANGE_ADMIN_PASSWORD_START";
export const CHANGE_ADMIN_PASSWORD_SUCCESS = "CHANGE_ADMIN_PASSWORD_SUCCESS";
export const CHANGE_ADMIN_PASSWORD_FAIL = "CHANGE_ADMIN_PASSWORD_FAIL";

export const GET_ALL_DIRECTOR_START = "GET_ALL_DIRECTOR_START";
export const GET_ALL_DIRECTOR_SUCCESS = "GET_ALL_DIRECTOR_SUCCESS";
export const GET_ALL_DIRECTOR_FAIL = "GET_ALL_DIRECTOR_FAIL";

//*Film Admin
export const GET_ALL_CATEGORY_START = "GET_ALL_CATEGORY_START";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAIL = "GET_ALL_CATEGORY_FAIL";

export const GET_ALL_FILM_START = "GET_ALL_FILM_START";
export const GET_ALL_FILM_SUCCESS = "GET_ALL_FILM_SUCCESS";
export const GET_ALL_FILM_FAIL = "GET_ALL_FILM_FAIL";

export const GET_ALL_RATE_START = "GET_ALL_RATE_START";
export const GET_ALL_RATE_SUCCESS = "GET_ALL_RATE_SUCCESS";
export const GET_ALL_RATE_FAIL = "GET_ALL_RATE_FAIL";

export const GET_ALL_FAVOURITE_START = "GET_ALL_FAVOURITE_START";
export const GET_ALL_FAVOURITE_SUCCESS = "GET_ALL_FAVOURITE_SUCCESS";
export const GET_ALL_FAVOURITE_FAIL = "GET_ALL_FAVOURITE_FAIL";

export const GET_ALL_SERIESFILM_START = "GET_ALL_SERIESFILM_START";
export const GET_ALL_SERIESFILM_SUCCESS = "GET_ALL_SERIESFILM_SUCCESS";
export const GET_ALL_SERIESFILM_FAIL = "GET_ALL_SERIESFILM_FAIL";

//*feedback

export const SEND_FEEDBACK_START = "SEND_FEEDBACK_START";
export const SEND_FEEDBACK_SUCCESS = "SEND_FEEDBACK_SUCCESS";
export const SEND_FEEDBACK_FAIL = "SEND_FEEDBACK_FAIL";
//* get all feedback
export const GET_FEEDBACK_START = "GET_FEEDBACK_START";
export const GET_FEEDBACK_SUCCESS = "GET_FEEDBACK_SUCCESS";
export const GET_FEEDBACK_FAIL = "GET_FEEDBACK_FAIL";

//*ReplyFeedback
export const REPLY_FEEDBACK_START = "REPLY_FEEDBACK_START";
export const REPLY_FEEDBACK_SUCCESS = "REPLY_FEEDBACK_SUCCESS";
export const REPLY_FEEDBACK_FAIL = "REPLY_FEEDBACK_FAIL";
//* Upload Adult
export const UPLOAD_ADULT_START = "UPLOAD_ADULT_START ";
export const UPLOAD_ADULT_SUCCESS = "UPLOAD_ADULT_SUCCESS";
export const UPLOAD_ADULT_FAIL = "UPLOAD_ADULT_FAIL";
//*Get All Adult
export const GET_ALL_ADULT_START = "GET_ALL_ADULT_START ";
export const GET_ALL_ADULT_SUCCESS = "GET_ALL_ADULT_SUCCESS";
export const GET_ALL_ADULT_FAIL = "GET_ALL_ADULT_FAIL";
//*Get All Kid
export const GET_ALL_KID_START = "GET_ALL_KID_START ";
export const GET_ALL_KID_SUCCESS = "GET_ALL_KID_SUCCESS";
export const GET_ALL_KID_FAIL = "GET_ALL_KID_FAIL";
